---
title: "Weekly Analysis"
---

Here we will provide a weekly description of the thought process behind any playoff eliminations.

**Week 15**

*Alabama, Iowa State, and UNLV\
(3 teams eliminated)\
(122 total eliminated)*

Here we are. The end of the 2024 regular season\* and conference championship games. We started with 134 teams. Each with a dream of being selected for the new 12-team College Football Playoff. One-by-one we eliminated 122 teams, only taking one mulligan (UNLV).

\*Army/Navy is the final regular season game of the 2024 season.

**Week 14**

*Army, Colorado, Ole Miss, Texas A&M, BYU, and Miami\
(6 teams eliminated + 1 team restored)\
(119 total eliminated)*

We waited until the release of this week's CFP Rankings and we are now down to 15 teams with viable paths to the CFP. Of these, 11 teams appear to be "Playoff Locks": Oregon, Penn State, Ohio State and Indiana (Big Ten), Texas, Georgia, and Tennessee (SEC), Notre Dame (Independent), SMU/Clemson Winner (ACC), Arizona State/Iowa Winner State (Big 12), and Boise State/UNLV Winner (Mountain West/Group of 5 Champion). That leaves one spot for an at-large team. Alabama, ranked 11th, is in the driver's seat. If SMU defeats Clemson, then Alabama should be in. If Clemson wins to "steal a bid", we'll have to wait to see how far SMU falls in the final rankings.

There has been a lot of noise this week around teams like Miami and South Carolina. This week's CFP Rankings seal their fate.

I had eliminated UNLV a few weeks ago as no two-loss Group of 5 team would have qualified for the 12-team playoff had it been in existence since 2014. However, here we are. UNLV is back in contention and needs only to beat Boise State to make a playoff appearance.

**Week 13**

*No Eliminations This Week\
(0 teams eliminated)\
(114 total eliminated)*

For the last few site updates I will be waiting until after the CFP Rankings are released each week as we are at a point in the season where eliminations may occur even if a team wins or does not play.

It felt like a lot happened this last week, but the CFP elimination scene is remarkably unchanged. In fact, I'm tempted to add Tulane and UNLV back into the list of non-eliminated teams as both may have something of a path to the playoff via a conference championship automatic bid. South Carolina was eliminated several weeks ago but is lurking.

Let's talk about a few teams on the fringe. Army is about as close to elimination as humanly possible. They need some serious chaos to stay in the conversation. If UNLV beats Nevada to qualify for the Mountain West Conference championship game, Army will be eliminated as they will have no realistic path to the fifth automatic bid. Colorado will be eliminated if they fail to qualify for the Big 12 Championship game. However, there remains a real possibility of the Big 12 champion being shut out of the playoff altogether. Arizona State, BYU and Iowa State are in a similar, but less dire situation. Alabama and Ole Miss will need some chaos, but maybe not severe chaos to keep their fading playoff hopes alive.

This weekend will go a very long way in providing some final clarity.

**Week 12**

*Kansas State, Louisiana, Louisville, LSU, Missouri, Pittsburgh, and Washington State\
*(7 teams eliminated)\
(114 total eliminated)

We got a significant narrowing of the field this week including two non-Power 4 teams exiting the playoff discussion. Just 20 teams remain for the 12 slots in the newly-expanded format. Let's do a quick conference roll call of the remaining contenders to see where we stand:

-   ACC: Clemson, Miami, and SMU. These three teams don't play each other in the regular season, but Miami and SMU have the inside track to the ACC Championship Game.. Clemson has completed their conference play.

-   Big 10: Indiana, Penn State, Ohio State, and Oregon. Ohio State and Indiana face-off this upcoming weekend. An Ohio State win puts the Buckeyes on course for a rematch with Oregon in the Big 10 Championship Game.

-   Big 12: BYU, Arizona State, Iowa State, Colorado. The BYU/Arizona State game looks to be a critical one. The winner will likely face a resurgent Colorado in the Big 12 title game.

-   SEC: Alabama, Georgia, Texas, Texas A&M, Ole Miss, Tennessee. There a number of chaotic scenarios that could play out in the SEC. The most likely path to the SEC Championship Game at this point leads to Alabama playing the winner of Texas/Texas A&M.

-   Notre Dame: The Fighting Irish are still alive and should make the playoff with ease if they win out. Recall that Notre Dame cannot receive a First Round bye as those are reserved for conference champions.

-   Group of 5: Army and Boise State. We're down to two Group of 5 contenders. Note that we eliminated Tulane in Week 3. Could they work their way back into the discussion if Army and Boise State implode?

**Week 11**

*Cincinnati, Iowa, Minnesota, Syracuse, and Texas Tech\
*(5 teams eliminated)\
(107 total eliminated)

Five more Power 4 teams are eliminated this week. We are down to only 27 teams with viable paths to the College Football Playoff. For some contrast, last year at this point only 9 teams remained in the hunt for the four-team playoff.

**Week 10**

*Navy, Memphis, Virginia Tech, Wake Forest, Duke, Illinois, Michigan, Wisconsin, Vanderbilt, Florida, Arkansas, TCU\
*(12 teams eliminated)\
(102 total eliminated)

The defending champions see their (already faint) hopes of a repeat snuffed out this week as more Power 4 teams are eliminated. Group of 5 teams Navy and Memphis see their dreams dashed. There are a hodgepodge of Power 4 teams with three losses that remain (in some way) in the race for their conference championship. It's a bit tough to decide what to do with them, but it seems increasingly unlikely that they will be able to work their way into the playoff picture.

The Group of 5 race for the playoffs is down to: Army, Boise State, Louisiana, and Washington State. Boise State is in the driver's seat here with Army not far behind. It'll be interesting to see the distance between these two teams in the first College Football Playoff poll (released on November 5th). Army has played a weak schedule, but has a chance to earn a statement win on November 23rd against Notre Dame. Even that might not be enough to propel them ahead of Boise State.

**Weeks 8 and 9**

*Georgia Tech, Virginia, Boston College, Stanford, West Virginia, Houston, Arizona, Utah, UCF, Oklahoma State, Nebraska, Michigan State, Washington, Maryland, Rutgers, Liberty, UNLV, South Carolina, Oklahoma, Kentucky, James Madison, UL Monroe, Northwestern, USC, North Texas\
*(25 teams eliminated)\
(90 total eliminated)

More travel and a bout with COVID put me a bit behind on this update, so I'll combine the updates for Week 8 and 9.

The list of Group of 5 teams with a shot at the playoff continues to dwindle as the last Conference USA team (Liberty) is eliminated with a shock loss to Kennesaw State. A whole host of Power 4 teams also see their playoff dreams evaporate. We're entering crunch time with lots of "elimination" games on tap in the next few weeks. The first official College Football Playoff rankings will be released on Tuesday, November 5th (certainly the most notable event taking place that day).

**Weeks 6 and 7**

*Florida State, California, NC State, North Carolina, Baylor, Kansas, Purdue, UCLA, Sam Houston, Toledo, Eastern Michigan, San Jose State, Oregon State, Mississippi State, Auburn, Coastal Carolina*\
(16 teams eliminated)\
(65 total eliminated)

I was out-of-town last week for work, so I'll combine the updates for Weeks 6 and 7.

At last! We say goodbye to several Power 4 conference teams! While several of these teams have long been eliminated from at-large contention, they still had some of a path to the playoff by winning their conference and being a top five conference champion. Those days have now passed. It might be worth taking a moment to see which Group of 5 teams have a path to the playoff. The list grows shorter by the day: Army, Navy, North Texas, Memphis, Liberty, Boise State, UNLV, Washington State (we'll consider them as an Independent for this purpose), James Madison, UL Monroe, and Louisiana. Boise State is currently the highest ranked Group of 5 team with Army and Navy not far behind.\

**Week 5**

*Western Kentucky, Buffalo, Northern Illinois, Fresno State, Georgia State, Texas State\
*(6 teams eliminated)\
(49 total eliminated)

We are oh so close to eliminating our first Power 4 conference teams. Teams like Florida State, Kansas, Houston, and Mississippi State are walking on thin ice and the ice is cracking beneath their feet. Why not eliminate them now? I'm taking a cautious approach to not eliminate Power 4 teams until they are mathematically incapable to winning their conference. I may need to adjust this approach in the future, but we'll keep it for now to be consistent.

**Week 4**

*East Carolina, South Florida, Louisiana Tech, Ball State, Ohio, Bowling Green, Georgia Southern, Marshall, Appalachian State, Arkansas State\
*(10 teams eliminated)\
(43 total eliminated)\
\
We continue saying "Goodbye!" to a variety of Group of 5 teams that hit the two loss threshold. We are getting ever closer to being Power 4 teams joining the ranks of the eliminated. Once a Power 4 team falls far enough back to be eliminated from conference championship contention, we can safely cast them aside. For some teams (even pretty bad teams) this may take awhile.

**Week 3**

*Rice, Tulane, Tulsa, UAB, UTSA, New Mexico State, Middle Tennessee, Florida International, UConn, Miami (OH), Central Michigan, Air Force, Colorado State, Hawai'i, San Diego State, Utah State, Southern Miss\
*(17 teams eliminated)\
(33 total eliminated)

This week we bid farewell to another set of Group of 5 teams as they pass over the bridge to two losses. While these teams could, technically, still win their conference, it seems unlikely that there would not be a better Group of 5 champion ranked above them. What about three loss Power 4 teams (e.g., Florida State)? These teams have not been mathematically eliminated from conference championship contention. However, as these teams compile more and more losses it seems exceedingly likely that, even if they won their conference, that a Group of 5 conference champion could pass them. Recall that no conference (not even the SEC and Big Ten) have an automatic berth in the playoff. Rather, the top five conference champions (from any conference) gain automatic entry into the playoff.

#### Week 2

*Charlotte, Florida Atlantic, Temple, Jacksonville State, UTEP, Massachusetts, Akron, Kent State, Western Michigan, New Mexico, Wyoming, Nevada, Old Dominion, South Alabama, Troy*\
(15 teams eliminated)\
(16 total eliminated)

The culling begins. It seems incredibly unlikely that the committee will award at-large bids to two loss non-Power 4 teams. Several teams hit this two loss threshold this week. UMass is an interesting case with both Missouri and Georgia left on the schedule. Would winning out and winning those two big games be enough? Probably not.

#### Weeks 0 and 1

*Kennesaw State* *\
*(1 team eliminated)\
(1 total eliminated)

This week we say goodbye to the Football Subdivision's newest member, Kennesaw State. As we noted in the Preseason analysis, Kennesaw is not eligible to win the Conference USA title. Their only path to the College Football Playoff would have been via an at-large berth (given to the top seven non-conference champions). The Owls Week 1 loss to UTSA ends those hopes.

A few other teams are teetering on the edge of the precipice (I'm looking at you New Mexico, UMass, and UConn). One more loss for UMass and UConn should send them sliding over the edge.

#### Preseason 2024

*(No Teams Eliminated)*

Each week we'll update the graphic on the home page to reflect the "elimination" of teams from the College Football Playoff (CFP) race.

I was ready to eliminate Kennesaw State (the newest member of the Football Bowl Subdivision) as new teams are typically ineligible for the postseason (with some exceptions) due to their transition period. While Kennesaw is bowl-eligible (if there are not enough teams available to fill the available bowl slots), Kennesaw is not eligible to win the Conference USA title. This precludes them from being a potential automatic CFP qualifier.

CFP spots are available to the five highest-ranked conference champions. Presumably, this will be the four power conference champions (ACC, Big Ten, Big 12, and SEC) plus the highest ranked Group of Five champion. Kennesaw State's only path (highly implausible, but not completely impossible) is to be selected as one of the seven at-large teams. We'll leave Kennesaw State as a "not eliminated" team for the moment, but a single loss will be enough to remove them from contention.

------------------------------------------------------------------------
